### ISSUE TITLE
Typo in Greedy strategies

### ISSUE THREAD

**Issue by RoyCoding8** [cp-tricki/cp-tricki.github.io#2]
![image](https://github.com/cp-tricki/cp-tricki.github.io/assets/92641125/1fefcadc-ba1f-483f-abd4-d0ca55775341)

There is a typo in the section 'greedy strategies'. In th image, we see that skill_1(A) is written instead of skill_1(B).

**Comment by miaowtin** [comment]
Fixed, thank you for pointing out!
